// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :exec
INSERT INTO projects (id, name, created_at, updated_at)
VALUES ($1, $2, $3, $4)
`

func (q *Queries) CreateProject(ctx context.Context, iD pgtype.UUID, name string, createdAt pgtype.Timestamptz, updatedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, createProject,
		iD,
		name,
		createdAt,
		updatedAt,
	)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, created_at, updated_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, created_at, updated_at
FROM projects
WHERE NOT $1::boolean
   OR (created_at, id) < ($2::timestamptz, $3::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

func (q *Queries) ListProjects(ctx context.Context, hasCursor bool, cursorCreatedAt pgtype.Timestamptz, cursorID pgtype.UUID, pageLimit int32) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects,
		hasCursor,
		cursorCreatedAt,
		cursorID,
		pageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
