// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: workspaces.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkspace = `-- name: CreateWorkspace :exec
INSERT INTO workspaces (project_id, document, version, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateWorkspaceParams struct {
	ProjectID pgtype.UUID
	Document  []byte
	Version   int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error {
	_, err := q.db.Exec(ctx, createWorkspace,
		arg.ProjectID,
		arg.Document,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT project_id, document, version, created_at, updated_at
FROM workspaces
WHERE project_id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, projectID pgtype.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, projectID)
	var i Workspace
	err := row.Scan(
		&i.ProjectID,
		&i.Document,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces
SET document = $1,
    version = $2,
    updated_at = $3
WHERE project_id = $4
  AND version = $5
RETURNING project_id, document, version, created_at, updated_at
`

type UpdateWorkspaceParams struct {
	Document        []byte
	NewVersion      int64
	UpdatedAt       pgtype.Timestamptz
	ProjectID       pgtype.UUID
	ExpectedVersion int64
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace,
		arg.Document,
		arg.NewVersion,
		arg.UpdatedAt,
		arg.ProjectID,
		arg.ExpectedVersion,
	)
	var i Workspace
	err := row.Scan(
		&i.ProjectID,
		&i.Document,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
