apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: claimbounty-api
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: claimbounty
      app.kubernetes.io/component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: claimbounty-web
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: claimbounty
      app.kubernetes.io/component: web
