apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: claimbounty
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 251m
    nginx.ingress.kubernetes.io/proxy-request-buffering: 'off'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '600'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Forwarded "";
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - claimbounty.example.invalid
      secretName: claimbounty-tls
  rules:
    - host: claimbounty.example.invalid
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: claimbounty-api
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: claimbounty-web
                port:
                  name: http
