apiVersion: v1
kind: ServiceAccount
metadata:
  name: claimbounty-api
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: claimbounty-worker
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: claimbounty-web
automountServiceAccountToken: false
