// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateProject(ctx context.Context, iD pgtype.UUID, name string, createdAt pgtype.Timestamptz, updatedAt pgtype.Timestamptz) error
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error
	GetProject(ctx context.Context, id pgtype.UUID) (Project, error)
	GetWorkspace(ctx context.Context, projectID pgtype.UUID) (Workspace, error)
	ListProjects(ctx context.Context, hasCursor bool, cursorCreatedAt pgtype.Timestamptz, cursorID pgtype.UUID, pageLimit int32) ([]Project, error)
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error)
}

var _ Querier = (*Queries)(nil)
