package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strconv"
)

func main() {
	files := []struct{ name, variable string }{
		{"case-manifest.schema.json", "caseManifestSchema"},
		{"audit-request.schema.json", "auditRequestSchema"},
		{"scientific-policy.schema.json", "scientificPolicySchema"},
		{"execution-policy.schema.json", "executionPolicySchema"},
	}
	output := "// Code generated by go generate; DO NOT EDIT.\n\npackage validation\n\n"
	for _, file := range files {
		contents, err := os.ReadFile(filepath.Join("..", "..", "..", "..", "..", "contracts", "schemas", "v1", file.name))
		if err != nil {
			panic(err)
		}
		output += fmt.Sprintf("const %s = %s\n\n", file.variable, strconv.Quote(string(contents)))
	}
	formatted, err := format.Source([]byte(output))
	if err != nil {
		panic(err)
	}
	root, err := os.OpenRoot(".")
	if err != nil {
		panic(err)
	}
	defer root.Close()
	if err := root.WriteFile("schemas_generated.go", formatted, 0o644); err != nil {
		panic(err)
	}
}
